# Generated by Django 5.1.2 on 2025-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
