# Generated by Django 5.1.2 on 2025-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificar', '0002_alertlog_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(choices=[('button', 'Botão'), ('geofence', 'Cerca Geográfica')], default='button', max_length=20),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='geofence_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
