# Generated by Django 5.1.6 on 2025-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paradasegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pa', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('embarcador', models.CharField(blank=True, choices=[('CORTEVA', 'CORTEVA'), ('BAYER', 'BAYER')], max_length=255, null=True)),
                ('transportador', models.CharField(blank=True, max_length=255, null=True)),
                ('placa_cavalo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_cavalo', models.ImageField(blank=True, null=True, upload_to='fotos_cavalo/')),
                ('foto_documento_cavalo', models.ImageField(blank=True, null=True, upload_to='fotos_documento_cavalo/')),
                ('placa_carreta', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_carreta', models.ImageField(blank=True, null=True, upload_to='fotos_carreta/')),
                ('foto_carreta_documento', models.ImageField(blank=True, null=True, upload_to='fotos_carreta_documento/')),
                ('nome_motorista', models.CharField(blank=True, max_length=255, null=True)),
                ('cnh', models.ImageField(blank=True, null=True, upload_to='fotos_motorista_documento/')),
                ('tipo_posto', models.CharField(blank=True, choices=[('0', '---'), ('1', 'POSTO DA SERRA'), ('2', 'POSTO BURITIZINHO'), ('3', 'POSTO BRASILEIRÃO'), ('4', 'POSTO TREVÃO'), ('5', 'POSTO JN'), ('6', 'POSTO CAPIXABOM'), ('7', 'POSTO GRAAL RUBI')], max_length=255, null=True)),
                ('descreva', models.CharField(blank=True, max_length=255, null=True)),
                ('id_rastreador', models.CharField(blank=True, max_length=255, null=True)),
                ('id_cadeado', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_parada', models.CharField(blank=True, choices=[('Pernoite', 'Pernoite'), ('Refeição', 'Refeição'), ('Check List', 'Check List')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='AGUARDANDO', max_length=50, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('ciente_do_projeto', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NAO')], max_length=50, null=True)),
                ('previsao_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('previsao_de_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('Horario_de_saida', models.CharField(blank=True, max_length=255, null=True)),
                ('inconformidade', models.CharField(blank=True, choices=[('NÃO', 'NÃO'), ('SENSOR PORTA MOTORISTA', 'SENSOR PORTA MOTORISTA'), ('SENSOR PORTA PASSAGEIRO', 'SENSOR PORTA PASSAGEIRO'), ('TECLADO', 'TECLADO'), ('BOTÃO DE PÂNICO', 'BOTÃO DE PÂNICO'), ('LACRE BAÚ', 'LACRE BAÚ'), ('SIRENE', 'SIRENE'), ('BLOQUEIO', 'BLOQUEIO'), ('CHAVE GERAL', 'CHAVE GERAL'), ('CNH', 'CNH'), ('DOCUMENTO DO VEÍCULO', 'DOCUMENTO DO VEÍCULO'), ('DOCUMENTO DA CARRETA', 'DOCUMENTO DA CARRETA'), ('OUTROS', 'OUTROS')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='passagemmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pa', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_do_posto', models.CharField(blank=True, choices=[('---', '---'), ('1', 'POSTO DA SERRA'), ('2', 'POSTO BURITIZINHO'), ('3', 'POSTO BRASILEIRÃO'), ('4', 'POSTO TREVÃO'), ('5', 'POSTO JN'), ('6', 'POSTO CAPIXABOM'), ('7', 'POSTO GRAAL RUBI')], max_length=255, null=True)),
                ('turno', models.CharField(blank=True, choices=[('Dia', 'Dia'), ('Noite', 'Noite')], max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('Iscas', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('notebook', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('celular', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('antena', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('bodycam', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('cadeados', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('drone', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('descrição', models.CharField(blank=True, choices=[('Não Confome', 'Não Confome'), ('Confome', 'Confome')], max_length=255, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
    ]
