# Generated by Django 5.1.6 on 2025-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='outros_embarcador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='embarcador',
            field=models.CharField(blank=True, choices=[('CORTEVA', 'CORTEVA'), ('BAYER', 'BAYER'), ('COMANDO LOG', 'COMANDO LOG'), ('OUTROS', 'OUTROS')], max_length=255, null=True),
        ),
    ]
