# Generated by Django 5.1.6 on 2025-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0002_paradasegura_outros_embarcador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paradasegura_ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='ponto/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
