# Generated by Django 5.1.6 on 2025-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('tipopessoa', models.CharField(blank=True, choices=[('Pessao Fisica', 'Pessoa Fisica'), ('Pessoa Juridica', 'Pessoa Juridica')], max_length=50, null=True)),
                ('razaosocial', models.CharField(blank=True, max_length=50, null=True)),
                ('nomefantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
